default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: HospitalApp_development


test:
  <<: *default
  database: HospitalApp_test




