default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: HospitalApp_development
  username: elvin
  password: 0063

test:
  <<: *default
  database: HospitalApp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
